name: Test solface

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.19.0
      - name: Test solface
        run: |
          go test ./... -v
      - name: Print solface version
        run: |
          go run ./... -version
